//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public long AttendanceId { get; set; }
        public long EmployeeDetailsId { get; set; }
        public Nullable<System.TimeSpan> SingIn { get; set; }
        public Nullable<System.TimeSpan> SingOut { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> HoursWorked { get; set; }
        public string Comment { get; set; }
        public string LogOutComment { get; set; }
        public string PCName { get; set; }
        public string Version { get; set; }
    }
}
