//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffLineActivity
    {
        public long OffLineActivityId { get; set; }
        public long EmployeeDetailsId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> OffLineTime { get; set; }
        public Nullable<System.TimeSpan> OnLineTime { get; set; }
        public Nullable<System.TimeSpan> ResumeTime { get; set; }
    }
}
